[package]
name = "driver_macros"
version = "0.0.0"
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
# External
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
